repos:
# dogfood
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.4.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: 21.7b0
  hooks:
    - id: black
      types: [python]
      language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==20.11.1']
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
    - id: isort
      types: [python]
      language_version: python3
