# known service, font, product, and people names
PROPER_NOUNS = [
    ".gitignore",
    "Consolas",
    "editorconfig",
    ".editorconfig",
    "Encrypt's",  # from "Let's Encrypt's"
    "Erdos",
    "3",
    "S3's",
    "amazonaws",
    "awscli",
    "certbot",
    "Firefox",
    "git",
    "gitignore",
    "github",
    "gmail",
    "gsuite",
    "gunicorn",
    "httpie",
    "Iceweasel",
    "kerberos",
    "ldap",
    "memcache",
    "memcached",
    "nanoc",
    "openapi",
    "openapi2",
    "openapi3",
    "sqlite",
    "sqlite3",
]
